sudo: required

env:
  - DOCKER_TAG="arcan1s/awesome-widgets-arch"

services:
  - docker

before_install:
  - docker build --tag="${DOCKER_TAG}" -f ".docker/Dockerfile-arch" ".docker"

scirpt:
  - docker run "${DOCKER_TAG}" ".docker/build-arch.sh"
