sudo: required

arch:
    packages:
        - plasma-framework
        # build deps
        - cmake
        - extra-cmake-modules
        - python
        # test
        - xorg-server-xvfb
    script:
        - export DISPLAY=:99.0
        - git clone https://github.com/arcan1s/awesome-widgets/
        - cd awesome-widgets && git submodule update --init --recursive
        - mkdir awesome-widgets/build
        - cd awesome-widgets/build && cmake -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_BUILD_TYPE=Optimization -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_FUTURE=ON -DBUILD_TESTING=ON ../sources
        - cd awesome-widgets/build && make
        - cd awesome-widgets/build && xvfb-run make test
        - sleep 3

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
