sudo: required
dist: trusty

language: cpp
os:
  - linux

before_install:
  - sudo sed -i 's/trusty/wily/g' /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get upgrade

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - extra-cmake-modules
      - g++
      - git
      - libkf5i18n-dev
      - libkf5notifications-dev
      - libkf5service-dev
      - libkf5windowsystem-dev
      - plasma-framework-dev
      - qtbase5-dev
      - qtdeclarative5-dev

before_script:
  - rm -rf build
  - mkdir build

script:
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ../sources
  - make
